apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ndelius-new-tech
  labels:
    app: ndelius-new-tech-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ndelius-new-tech-app
  template:
    metadata:
      labels:
        app: ndelius-new-tech-app
    spec:
      containers:
        - name: ndelius-new-tech
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/probation-services/ndelius-new-tech:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: '8000'
            - name: ANALYTICS_MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: ndelius-new-tech-secret
                  key: mongoConnection
            - name: ANALYTICS_MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: mongoDatabase
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: ndelius-new-tech-secret
                  key: applicationSecret
            - name: CUSTODY_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ndelius-new-tech-secret
                  key: custodyApiPassword
            - name: CUSTODY_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ndelius-new-tech-secret
                  key: custodyApiUsername
            - name: ELASTIC_SEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: elasticSearchHost
            - name: ELASTIC_SEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: elasticSearchPort
            - name: ELASTIC_SEARCH_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: elasticSearchScheme
            - name: NOMIS_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: nomisApiBaseUrl
            - name: PRISONER_API_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: prisonerApiProvider
            - name: DELIUS_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: communityApiBaseUrl
            - name: PARAMS_USER_TOKEN_VALID_DURATION
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: userTokenDuration
            - name: PDF_GENERATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: pdfGeneratorUrl
            - name: STORE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: ndelius-new-tech-config
                  key: storeProvider









