branch-defaults:
  master:
    environment: delius-new-tech-secure
environment-defaults:
  delius-new-tech:
    branch: null
    repository: null
global:
  application_name: delius-new-tech
  default_ec2_keyname: null
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: /workspace/ndelius2.jar