version: 2
general:
  branches:
jobs:
    build:
        working_directory: ~/ndelius-new-tech
        docker:
            - image: circleci/openjdk:8-node-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: Run sbt build
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1024m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  sbt assembly < /dev/null
            - save_cache:
                key: v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                paths:
                  - ~/.ivy2/cache
                  - ~/.sbt
            - store_test_results:
                path: ./target/test-reports/
            - run:
                name: Save Fat Jar
                command: |
                  mkdir -p ./target/artifacts
                  rm target/scala-2.12/ndelius2_*-web-assets.jar
                  mv target/scala-2.12/*.jar ./target/artifacts/
                  ls -1 ./target/artifacts/ndelius2-*.jar | sed 's/^.*ndelius2-\(.*\)\.jar.*$/\1/' > ./target/artifacts/version.txt
                  cp ./target/artifacts/ndelius2*.jar ./target/artifacts/ndelius2.jar
            - persist_to_workspace:
                root: ./target/artifacts/
                paths:
                  - ./ndelius2.jar
                  - ./version.txt
            - store_artifacts:
                path: target/artifacts
                destination: jars
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    deploysmoketest:
        docker:
          - image: paulodiovani/aws-eb-cli
        working_directory: ~/ndelius-new-tech
        steps:
        - attach_workspace:
            at: /workspace
        - checkout
        - run:
            name: Deploy to Elastic Beanstalk Smoke Test environment
            command: |
                export PATH=$PATH:~/.local/bin/
                eb deploy delius-new-tech-smoke-test --label $(cat /workspace/version.txt)
    smoketest:
        docker:
            - image: circleci/openjdk:8-node-browsers
        working_directory: ~/ndelius-new-tech
        steps:
        - run:
            name: Checkout smoke test
            command: |
                git clone https://github.com/noms-digital-studio/ndelius-new-tech-smoke-test.git .
                git checkout "$CIRCLE_BRANCH" || true
        - run:
            name: Build and run test
            command: |
                gradle test
        - store_test_results:
            path: ./build/test-results/
        - store_test_results:
            path: ./build/geb-reports/
        - store_test_results:
            path: ./build/reports/
        - store_artifacts:
            path: ./build/test-results/
            destination: reports
        - store_artifacts:
            path: ./build/geb-reports/
            destination: reports
        - store_artifacts:
            path: ./build/reports/
            destination: reports
    deploy:
        docker:
          - image: paulodiovani/aws-eb-cli
        working_directory: ~/ndelius-new-tech
        steps:
        - attach_workspace:
            at: /workspace
        - checkout
        - run:
            name: Deploy to Elastic Beanstalk
            command: |
                eb deploy --label $(cat /workspace/version.txt)

workflows:
    version: 2
    build-deploy-test:
        jobs:
            - build
            - deploysmoketest:
                requires:
                    - build
            - smoketest:
                requires:
                    - deploysmoketest
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                      only: master