version: 2
general:
  branches:
jobs:
    build:
        working_directory: ~/ndelius-new-tech
        docker:
            - image: openjdk:8
        steps:
            - checkout
            - restore_cache:
                keys:
                  - sbt-{{ checksum "build.sbt" }}
                  - sbt-
            - setup_remote_docker
            - run:
                name: Install sbt into build container
                command: |
                    apt-get update
                    apt-get install apt-transport-https
                    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
                    echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
                    apt-get update
                    apt-get install sbt
            - run:
                name: Run sbt build
                command: |
                  curl -sL https://deb.nodesource.com/setup_8.x | bash -
                  apt-get install -y nodejs
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  sbt assembly
            - save_cache:
                key: sbt-{{ checksum "build.sbt" }}
                paths:
                  - ~/.ivy2/cache
                  - ~/.sbt
            - run:
                name: Save test results
                command: |
                  mkdir -p ~/junit/
                  find . -type f -regex ".*/target/test-reports/.*xml" -exec cp {} ~/junit/ \;
                when: always
            - run:
                name: Save Fat Jar
                command: |
                  mkdir -p ./target/artifacts
                  mv target/scala-2.12/*.jar ./target/artifacts/
            - store_artifacts:
                path: target/artifacts
                destination: jars
            - store_artifacts:
                path: ~/junit
                destination: reports
            - store_test_results:
                path: ~/junit
