defaults: &defaults
  working_directory: ~/ndelius-new-tech
  docker:
    - image: circleci/openjdk:8-node-browsers

version: 2
general:
  branches:
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: npm install
                command: |
                  npm install < /dev/null
            - run:
                name: Compile
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  sbt compile < /dev/null
            - persist_to_workspace:
                  root: .
                  paths: .
    unitTests:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: Unit tests
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags @None"
                  sbt test < /dev/null
            - store_test_results:
                path: ./target/test-reports/
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    bddOfffenderSummary:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: BDD - Offender Summary
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags @OffenderSummary"
                  sbt "test-only bdd.RunCucumber" < /dev/null
            - store_test_results:
                path: ./target/test-reports/
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    bddSFR:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: BDD - SFR
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags @SFR"
                  sbt "test-only bdd.RunCucumber" < /dev/null
            - store_test_results:
                path: ./target/test-reports/
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    parallel:
        <<: *defaults
        parallelism: 2
        steps:
            - attach_workspace:
                at: ~/ndelius-new-tech
            - run:
                name: BDD - Test
                command: |
                  export TESTFILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings --timings-type=filename)
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags @Parom1 $TESTFILES"
                  echo $TESTFILES
                  echo $CUCUMBER_OPTIONS
    bddParom1:
        <<: *defaults
        parallelism: 2
        steps:
            - attach_workspace:
                  at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: BDD - Parom1
                command: |
                  export TESTFILES=$(circleci tests glob "features/paroleparom1report/*.feature" | circleci tests split --split-by=timings --timings-type=filename)
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags @Parom1 $TESTFILES"
                  echo $TESTFILES
                  echo $CUCUMBER_OPTIONS
            - store_test_results:
                path: ./target/test-reports/
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    bddOther:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: BDD - Others
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  export CUCUMBER_OPTIONS="--tags ~@Parom1 --tags ~@OffenderSummary --tags ~@SFR"
                  sbt "test-only bdd.RunCucumber" < /dev/null
            - store_test_results:
                path: ./target/test-reports/
            - store_artifacts:
                path: ./target/test-reports/
                destination: reports
    artifacts:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/ndelius-new-tech
            - restore_cache:
                keys:
                  - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                  - v2-ndelius-new-tech-
            - run:
                name: Run sbt assembly
                command: |
                  export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
                  export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
                  sbt 'set test in assembly := {}' assembly < /dev/null
            - save_cache:
                key: v2-ndelius-new-tech-{{ checksum "build.sbt" }}
                paths:
                  - ~/.ivy2/cache
                  - ~/.sbt
            - run:
                name: Save Fat Jar
                command: |
                  mkdir -p ./target/artifacts
                  rm target/scala-2.12/ndelius2_*-web-assets.jar
                  mv target/scala-2.12/*.jar ./target/artifacts/
                  ls -1 ./target/artifacts/ndelius2-*.jar | sed 's/^.*ndelius2-\(.*\)\.jar.*$/\1/' > ./target/artifacts/version.txt
                  cp ./target/artifacts/ndelius2*.jar ./target/artifacts/ndelius2.jar
            - persist_to_workspace:
                root: ./target/artifacts/
                paths:
                  - ./ndelius2.jar
                  - ./version.txt
            - store_artifacts:
                path: target/artifacts
                destination: jars
    deploysmoketest:
        docker:
          - image: paulodiovani/aws-eb-cli
        working_directory: ~/ndelius-new-tech
        steps:
        - attach_workspace:
            at: /workspace
        - checkout
        - run:
            name: Deploy to Elastic Beanstalk Smoke Test environment
            command: |
                export PATH=$PATH:~/.local/bin/
                eb deploy delius-new-tech-2-secure --label $(cat /workspace/version.txt)
    smoketest:
        docker:
            - image: circleci/openjdk:8-node-browsers
        working_directory: ~/ndelius-new-tech
        steps:
        - run:
            name: Checkout smoke test
            command: |
                git clone https://github.com/noms-digital-studio/ndelius-new-tech-smoke-test.git .
                git checkout "$CIRCLE_BRANCH" || true
        - run:
            name: Build and run test
            command: |
                gradle test
    deploy:
        docker:
          - image: paulodiovani/aws-eb-cli
        working_directory: ~/ndelius-new-tech
        steps:
        - attach_workspace:
            at: /workspace
        - checkout
        - run:
            name: Deploy to Elastic Beanstalk
            command: |
                eb deploy --label $(cat /workspace/version.txt)

workflows:
    version: 2
    build-deploy-test:
        jobs:
            - build
            - parallel:
                requires:
                    - build
            - bddParom1:
                requires:
                    - build
            - artifacts:
                requires:
                    - parallel
                    - bddParom1
            - deploysmoketest:
                requires:
                    - artifacts
            - smoketest:
                requires:
                    - deploysmoketest
            - deploy:
                requires:
                    - artifacts
                filters:
                    branches:
                      only: master