defaults: &defaults
  working_directory: ~/ndelius-new-tech
  docker:
    # dangerous pinning to old version with node v12.18.1 - from previous version of circleci/openjdk:8-node-browsers
    # fixes issue with compatible issue with v12.18.3 and graceful-fs webjar
    - image: circleci/openjdk@sha256:0ab7db4ecdc5966baaa44f64075725c22a53dc63922492c26cabd98b7c961ae0

version: 2.1

orbs:
  mem: circleci/rememborb@0.0.1
  hmpps: ministryofjustice/hmpps@7

general:
  branches:
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: yarn install
          command: |
            yarn install --silent
      - run:
          name: Compile
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            sbt compile < /dev/null
      - persist_to_workspace:
          root: .
          paths: .
  unitTests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: Unit tests (Jest)
          command: |
            yarn jest /app/assets/javascripts/app
      - run:
          name: Unit tests
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags @None"
            sbt test < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  bddOffenderSummary:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: BDD - Offender Summary
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags @OffenderSummary"
            sbt "test-only bdd.RunCucumber" < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  bddNationalSearch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: BDD - National Search
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags @Search"
            sbt "test-only bdd.RunCucumber" < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  bddSFR:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: BDD - SFR
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags @SFR"
            sbt "test-only bdd.RunCucumber" < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  bddParom1:
    <<: *defaults
    parallelism: 3
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: BDD - Parom1
          command: |
            export TESTFILES=$(circleci tests glob "features/**/paroleparom1report/*.feature" | circleci tests split --split-by=timings --timings-type=filename)
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags @Parom1 $TESTFILES"
            echo $CUCUMBER_OPTIONS
            sbt "test-only bdd.RunCucumber" < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  bddOther:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: BDD - Others
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            export CUCUMBER_OPTIONS="--tags ~@Parom1 --tags ~@OffenderSummary --tags ~@SFR"
            sbt "test-only bdd.RunCucumber" < /dev/null
      - store_test_results:
          path: ./target/test-reports/
      - store_artifacts:
          path: ./target/test-reports/
          destination: reports
  artifacts:
    <<: *defaults
    steps:
      - hmpps/create_app_version
      - attach_workspace:
          at: ~/ndelius-new-tech
      - restore_cache:
          keys:
            - v2-ndelius-new-tech-{{ checksum "build.sbt" }}
            - v2-ndelius-new-tech-
      - run:
          name: Run sbt assembly
          command: |
            export _JAVA_OPTIONS="-Xms512m -Xmx1224m"
            export APP_VERSION="${VERSION}"
            export SBT_OPTS="${SBT_OPTS} -Dsbt.jse.engineType=Node -Dsbt.jse.command=$(which nodejs)"
            sbt 'set test in assembly := {}' assembly < /dev/null
      - save_cache:
          key: v2-ndelius-new-tech-{{ checksum "build.sbt" }}
          paths:
            - ~/.ivy2/cache
            - ~/.sbt
      - run:
          name: Save Fat Jar
          command: |
            mkdir -p ./target/artifacts
            rm target/scala-2.12/ndelius2_*-web-assets.jar
            cp target/scala-2.12/*.jar ./target/artifacts/
            cp ./target/artifacts/ndelius2*.jar ./target/artifacts/ndelius2.jar
      - persist_to_workspace:
          root: ./target/artifacts/
          paths:
            - ./ndelius2.jar
      - store_artifacts:
          path: target/artifacts
          destination: jars
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Create IMAGE_NAME env var
          command: echo "export IMAGE_NAME=quay.io/hmpps/ndelius-new-tech" >> $BASH_ENV
      - mem/remember:
          env_var: IMAGE_NAME
          value: "${IMAGE_NAME}"
      - run:
          name: Build and push container image
          command: |
            docker build --pull \
              --rm=false . \
              --build-arg BUILD_NUMBER=$APP_VERSION \
              --build-arg GIT_REF=$CIRCLE_SHA1 \
              --build-arg GIT_BRANCH=$CIRCLE_BRANCH \
              --tag "${IMAGE_NAME}:${APP_VERSION}" \
              --label "app.version=${APP_VERSION}" \
              --label "build.version=${APP_VERSION}" \
              --label "build.number=${CIRCLE_BUILD_NUM}" \
              --label "build.url=${CIRCLE_BUILD_URL}" \
              --label "build.gitref=${CIRCLE_SHA1}"
            docker login -u="${QUAYIO_USERNAME}" -p="${QUAYIO_PASSWORD}" quay.io
            docker tag "${IMAGE_NAME}:${APP_VERSION}" "${IMAGE_NAME}:latest"
            docker push "${IMAGE_NAME}:${APP_VERSION}"
            docker push "${IMAGE_NAME}:latest"

workflows:
  version: 2
  build-deploy-test:
    jobs:
      - build
      - bddOther:
          requires:
            - build
      - bddParom1:
          requires:
            - build
      - bddSFR:
          requires:
            - build
      - bddOffenderSummary:
          requires:
            - build
      - bddNationalSearch:
          requires:
            - build
      - unitTests:
          requires:
            - build
      - artifacts:
          requires:
            - build
            - bddOther
            - bddSFR
            - unitTests
      - hmpps/deploy_env:
          name: deploy_test
          env: "test"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - master
          requires:
            - artifacts
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-delius-core-preprod
          filters:
            branches:
              only:
                - master
          requires:
            - artifacts
      - request-prod-approval:
          type: approval
          requires:
            - deploy_test
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: probation-integration-notifications
          context:
            - hmpps-common-vars
            - hmpps-delius-core-prod
          requires:
            - request-prod-approval
