---
generic-service:
  replicaCount: 2
  ingress:
    host: ndelius-new-tech.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_BASE_URL: https://sign-in.hmpps.service.justice.gov.uk/
    PROBATION_OFFENDER_SEARCH_URL: https://probation-offender-search.hmpps.service.justice.gov.uk/
    NOMIS_API_BASE_URL: https://prison-api.prison.service.justice.gov.uk/
    STORE_ALFRESCO_URL: https://alfresco.probation.service.justice.gov.uk/alfresco/service/

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  businessHoursOnly: true