---
generic-service:
  replicaCount: 2
  ingress:
    host: ndelius-new-tech-test.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_BASE_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/
    PROBATION_OFFENDER_SEARCH_URL: https://probation-offender-search-dev.hmpps.service.justice.gov.uk/
    NOMIS_API_BASE_URL: https://prison-api-dev.prison.service.justice.gov.uk/
    STORE_ALFRESCO_URL: https://hmpps-delius-alfresco-test.apps.live.cloud-platform.service.justice.gov.uk/alfresco/service/

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  businessHoursOnly: true