---
generic-service:
  replicaCount: 2
  ingress:
    host: ndelius-new-tech-preprod.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_BASE_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/
    PROBATION_OFFENDER_SEARCH_URL: https://probation-offender-search-preprod.hmpps.service.justice.gov.uk/
    NOMIS_API_BASE_URL: https://prison-api-preprod.prison.service.justice.gov.uk/
    STORE_ALFRESCO_URL: https://alfresco.pre-prod.delius.probation.hmpps.dsd.io/alfresco/service/

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  businessHoursOnly: true