---
generic-service:
  replicaCount: 2
  ingress:
    host: ndelius-new-tech-test.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_BASE_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/
    PROBATION_OFFENDER_SEARCH_URL: https://probation-offender-search-dev.hmpps.service.justice.gov.uk/
    NOMIS_API_BASE_URL: https://prison-api-dev.prison.service.justice.gov.uk/
    STORE_ALFRESCO_URL: https://hmpps-delius-alfresco-test.apps.live.cloud-platform.service.justice.gov.uk/alfresco/service/

  scheduledDowntime:
    enabled: true

  allowList:
    groups:
      - moj_cloud_platform
      - digital_staff_and_mojo
      - unilink_staff
    delius-test-1: "35.176.126.163/32"
    delius-test-2: "35.178.162.73/32"
    delius-test-3: "52.56.195.113/32

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  businessHoursOnly: true
